import { ShopProvider } from './context/shopContext';
import { Cairo } from 'next/font/google';
import { fetchProducts } from '@/lib/fetchProducts';
import { ToastContainer, toast } from 'react-toastify';
import {NextIntlClientProvider, hasLocale} from 'next-intl';
import {notFound} from 'next/navigation';
import {routing} from '../../i18n/routing';

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from './components/Header';
import axios from 'axios';
import Footer from './components/footer';



const inter = Cairo({
  subsets: ['arabic'],
  weight: ['400', '500', '700'], // الأوزان التي تريدها
  display: 'swap',
  variable: '--font-cairo',
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Kamsed-store",
  description: "Generated by create next app",
};

export default async function RootLayout({ children,params }) {

  const { locale } = await params;

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

const products = await fetchProducts();
  
 

  return (
    <html lang={locale}  >

      <body
        className={inter.className}
      >
        <ToastContainer/>
        <div className='xl:px-20 lg:px-10 relative sm:px-0'>
          <ShopProvider initialProducts={products}  >
             <NextIntlClientProvider>
            <Header  />
            {children}
           
             <Footer/>
            </NextIntlClientProvider>
          </ShopProvider>
        </div>
      </body>
    </html>
  );
}
